### ISSUE TITLE
推荐一些库

### ISSUE THREAD

**Issue by xiaotupansy** [jobbole/awesome-dotnet-cn#13]
AppMetrics 地址：https://github.com/AppMetrics/AppMetrics
.net core & .net framework 下的监控

Polly 地址：https://github.com/App-vNext/Polly
.net core & .net framework 下的瞬时错误状态处理库

BenchmarkDotNet 地址：https://github.com/dotnet/BenchmarkDotNet
.net core & .net framework 下的用来跑benchmark的库

AspectCore-Framework 地址：https://github.com/dotnetcore/AspectCore-Framework
.net core 下的AOP库

CAP 地址：https://github.com/dotnetcore/CAP
.net core 下的分布式事务处理库

EntityFramework-Plus 地址：https://github.com/zzzprojects/EntityFramework-Plus
.net core & .net framework 下EF扩展库

另外建议多加入一些docker相关的内容。
比如基础的aspnetcore基础运行镜像：
https://hub.docker.com/r/microsoft/aspnetcore/

**Comment by tangyouhua** [comment]
收到，感谢！已把您加入贡献者列表。

Polly 目前已收录。

提交的资源加入到列表，其中
AspectCore-Framework Star数不要500，暂不收录
